// libs/angular-sky/src/components/flow-card.component.ts
// libs/angular-sky/src/components/flow-card.component.ts
import { Component, Input, ElementRef, ViewChild, effect, inject, signal } from '@angular/core';
import { SkyService } from '../shell/sky-shell.service';
import { getSkyMermaidConfig } from '@sky-ui/shared-utils';
import mermaid from 'mermaid';

@Component({
  selector: 'sky-flow-card',
  standalone: true,
  template: `
    <div class="sky-glass-stratus rounded-xl p-4 border-white/5">
      <div #mermaidTarget class="mermaid-target"></div>
    </div>
  `,
  styles: [`
    :host ::ng-deep svg { max-width: 100%; height: auto; }
    :host ::ng-deep .node rect { fill-opacity: 0.2 !important; stroke-width: 1px !important; }
  `]
})
export class FlowCardComponent {
  definition = Input.required<string>();
  id = Input.required<string>();
  
  @ViewChild('mermaidTarget') target!: ElementRef;
  private sky = inject(SkyService);

  constructor() {
    effect(async () => {
      const theme = this.sky.theme();
      mermaid.initialize(getSkyMermaidConfig(theme));
      
      const { svg } = await mermaid.render(`ang-mermaid-${this.id()}`, this.definition());
      this.target.nativeElement.innerHTML = svg;
    });
  }
}

// libs/react-sky/src/components/FlowCard.tsx
// libs/react-sky/src/components/FlowCard.tsx
import React, { useEffect, useRef, useState } from 'react';
import mermaid from 'mermaid';
import { useSky } from '../shell/SkyShell';
import { getSkyMermaidConfig } from '@sky-ui/shared-utils';

export const FlowCard = ({ chartDefinition, id }: { chartDefinition: string, id: string }) => {
  const { theme } = useSky();
  const [svg, setSvg] = useState('');
  const containerRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    mermaid.initialize(getSkyMermaidConfig(theme));
    
    mermaid.render(`mermaid-${id}`, chartDefinition).then(({ svg }) => {
      setSvg(svg);
    });
  }, [chartDefinition, theme, id]);

  return (
    <div className="sky-glass-stratus rounded-xl p-4 border-white/5 overflow-hidden transition-all duration-500">
      <div 
        className="mermaid-container opacity-80 hover:opacity-100 transition-opacity"
        dangerouslySetInnerHTML={{ __html: svg }} 
      />
      <style jsx global>{`
        .mermaid-container svg {
          height: auto;
          width: 100%;
          filter: drop-shadow(0 0 5px rgba(103, 232, 249, 0.2));
        }
        .mermaid-container rect {
          rx: 8px; /* Rounded glass nodes */
        }
      `}</style>
    </div>
  );
};
