// libs/angular-sky/src/general/sky-nav.component.ts
import { Component, Input } from "@angular/core";
import { SkyCardComponent } from "./sky-card.component";

type SkyNavOrientation = "horizontal" | "vertical";

@Component({
  selector: "sky-nav",
  standalone: true,
  imports: [SkyCardComponent],
  template: `
    <sky-card
      blur="nimbus"
      [theme]="theme()"
      [rounded]="rounded()"
      padding="0.9rem 1rem"
    >
      <div
        class="flex min-w-0"
        [class.flex-col]="orientation() === 'vertical'"
        [class.items-stretch]="orientation() === 'vertical'"
        [class.gap-2.5]="orientation() === 'vertical'"
        [class.flex-row]="orientation() === 'horizontal'"
        [class.flex-wrap]="orientation() === 'horizontal'"
        [class.items-center]="orientation() === 'horizontal'"
        [class.gap-3]="orientation() === 'horizontal'"
        [class.md:gap-4]="orientation() === 'horizontal'"
      >
        <ng-content></ng-content>
      </div>
    </sky-card>
  `,
})
export class SkyNavComponent {
  theme = Input<"midnight" | "daylight">("midnight");
  orientation = Input<SkyNavOrientation>("horizontal");
  rounded = Input(true);
}

// libs/react-sky/src/components/SkyNav.tsx
import React from 'react';
import { SkyCard } from './SkyCard';

type SkyNavProps = React.HTMLAttributes<HTMLDivElement> & {
  theme?: 'midnight' | 'daylight';
  orientation?: 'horizontal' | 'vertical';
  rounded?: boolean;
};

export const SkyNav = ({
  children,
  className = '',
  theme = 'midnight',
  orientation = 'horizontal',
  rounded = true,
  ...props
}: SkyNavProps) => {
  const layoutClassName =
    orientation === 'vertical'
      ? 'flex-col items-stretch gap-2.5'
      : 'flex-row flex-wrap items-center gap-3 md:gap-4';

  return (
    <SkyCard blur="nimbus" theme={theme} rounded={rounded} className={`sky-nav px-4 py-3 ${className}`.trim()} {...props}>
      <div className={`flex min-w-0 ${layoutClassName}`.trim()}>{children}</div>
    </SkyCard>
  );
};
